credentials:
  usernames:
    hmblstreamlit:
      email: ''
      name: HMBL Streamlit
      password: "$2b$12$LreroND.nvZ7n2owuHITj.zTigGbkdOnXM29AhJUloDlmpojayY9S"

cookie:
  expiry_days: 30
  key: grid2026_auth_secret_key
  name: grid2026_auth
